default:
  client_id: "REPLACE_WITH_CLIENT_ID"
  client_secret: "REPLACE_WITH_CLIENT_SECRET"
  resource: "https://uswe.datahub.connect.aveva.com"
  api_version: "v1"
  tenant: "REPLACE_WITH_TENANT_ID"
  namespace: "REPLACE_WITH_NAMESPACE_ID"
  test_only_dataview_id: "WindTurbineData"
  test_only_start_index: "3/11/2020 00:00:00"
  test_only_end_index: "3/11/2020 02:00:00""
  test_only_interval: "00:00:05"
